force-app/main/default/objects/Studenti__c/Studenti__c.object-meta.xml
<CustomObject>
    <label>Studenti</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Studenti Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Studenti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Studenti__c/fields/CognomeStudente__c.field-meta.xml
<CustomField>
    <fullName>CognomeStudente__c</fullName>
    <label>Cognome Studente</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Studenti__c/fields/Corsi__c.field-meta.xml
<CustomField>
    <fullName>Corsi__c</fullName>
    <label>Corsi</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Matematica</fullName>
            </value>
            <value>
                <fullName>Italiano</fullName>
            </value>
            <value>
                <fullName>Geografia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Studenti__c/fields/NomeStudente__c.field-meta.xml
<CustomField>
    <fullName>NomeStudente__c</fullName>
    <label>Nome Studente</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Studenti__c/fields/Privacy__c.field-meta.xml
<CustomField>
    <fullName>Privacy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Privacy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Student.cls
public  class Student {
    @AuraEnabled
    public static String insertStudent(Studenti__c studenti) {
        upsert studenti;
        return studenti.Id;
    }
    @AuraEnabled(cacheable=true)
    public static List<Studenti__c> getStudentiList() {
        return [
            SELECT Id, NomeStudente__c, CognomeStudente__c, Password__c, Corsi__c, Privacy__c
            FROM Studenti__c
        ];
    }
    @AuraEnabled
    public static void insertDescription(String id, String description) {
        Studenti__c stud=[SELECT Id, Description__c FROM Studenti__c WHERE Id=:id];
        stud.Description__c=description;
        update stud;
    }
}